# Generated by Django 4.2.5 on 2024-11-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_test_data'),
    ]

    operations = [

    ]
