# Generated by Django 4.2.5 on 2024-11-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
