# Generated by Django 4.2.5 on 2024-12-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_line_user_id_alter_user_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(db_comment='ロール:user:0, admin:1'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(blank=True, db_comment='ユーザー名', max_length=256, null=True),
        ),
    ]
