# Generated by Django 4.2.5 on 2024-11-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(db_comment='商品番号', max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_comment='商品名', max_length=255)),
                ('description', models.TextField(blank=True, db_comment='商品説明', null=True)),
                ('allergens', models.CharField(blank=True, db_comment='アレルゲン', max_length=255, null=True)),
                ('product_price', models.IntegerField(db_comment='商品価格')),
                ('product_marque', models.CharField(blank=True, db_comment='商品型番:商品型号，待定', max_length=100, null=True)),
                ('product_store_barcode', models.CharField(blank=True, db_comment='商品の倉庫バーコード', max_length=100, null=True)),
                ('product_size_information', models.CharField(blank=True, db_comment='商品サイズ情報:（json数组-重量，体积，规格等）', max_length=255, null=True)),
                ('sale_status', models.IntegerField(blank=True, db_comment='販売状況:"01販売中，02販売停止"', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時')),
                ('updated_by', models.CharField(blank=True, db_comment='更新者', max_length=256, null=True)),
                ('created_by', models.CharField(blank=True, db_comment='登録者', max_length=256, null=True)),
                ('deleted_flag', models.BooleanField(blank=True, db_comment='削除フラグ', null=True)),
            ],
            options={
                'db_table': 'products',
                'db_table_comment': '商品',
            },
        ),
    ]
