# Generated by Django 4.2.5 on 2024-11-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='webpageUrl',
            field=models.URLField(blank=True, db_comment='サイトURL', max_length=2083, null=True),
        ),
    ]
