# Generated by Django 4.2.5 on 2024-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_add_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, db_comment='商品画像URL', null=True),
        ),
    ]
