# Generated by Django 4.2.5 on 2024-11-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.CharField(db_comment='チャットID', max_length=50, primary_key=True, serialize=False)),
                ('questions', models.TextField(blank=True, db_comment='問題', null=True)),
                ('answers', models.TextField(blank=True, db_comment='答え', null=True)),
                ('token_utilization', models.IntegerField(db_comment='token消費量')),
                ('thread_id', models.CharField(blank=True, db_comment='スレッドID', max_length=256, null=True)),
                ('created_by', models.CharField(blank=True, db_comment='作成者', max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, db_comment='更新者', max_length=256, null=True)),
                ('deleted_flag', models.BooleanField(blank=True, db_comment='削除フラグ', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='更新日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='作成日時')),
            ],
            options={
                'db_table': 'line.chat_histories',
                'db_table_comment': 'チャット歴史',
            },
        ),
    ]
