# Generated by Django 4.2.5 on 2024-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='assistant_id',
            field=models.CharField(blank=True, db_comment='assistant ID', max_length=256, null=True),
        ),
    ]
