# Generated by Django 4.2.5 on 2024-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chathistory_assistant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('openai_thread_id', models.CharField(blank=True, max_length=256, null=True)),
                ('user_id', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_flag', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'threads',
            },
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='assistant_id',
        ),
    ]
