# Generated by Django 4.2.5 on 2024-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_estimated_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(db_comment='注文ステータス:"01支払い待ち"、"02支払い済み"、"03発送済み"、"04配送完了"、"05キャンセル"'),
        ),
    ]
